services:
  web:
    build: .
    ports:
      # This is the main port for your application.
      - "2525:80" 
    volumes:
      - ./src:/usr/share/nginx/html
    # THIS IS THE NEW, IMPORTANT PART:
    depends_on:
      - proxy

  proxy:
    build:
      context: ./proxy
    # No ports need to be exposed here.
    env_file:
      - .env