services:
  web:
    build: .
    # The 'ports' section is not strictly necessary for Traefik, but is harmless.
    ports:
      - "2525:80"
    volumes:
      - ./src:/usr/share/nginx/html
    # This service MUST be on the same network as Traefik.
    networks:
      - t3_proxy # Correct network from your Portainer screenshot
    labels:
      # --- Traefik Labels ---
      - "traefik.enable=true"
      
      # Tell Traefik to use this specific network to connect to this service
      - "traefik.docker.network=t3_proxy"

      # --- Router for HTTP Traffic ---
      # !!! IMPORTANT: Replace 'your-domain.com' with your actual domain name !!!
      - "traefik.http.routers.my-website-http.rule=Host(`gazaka.com`)"
      - "traefik.http.routers.my-website-http.entrypoints=web"

      # --- Middleware for HTTPS Redirect (Recommended) ---
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.my-website-http.middlewares=https-redirect"

      # --- Router for HTTPS Traffic ---
      # !!! IMPORTANT: Replace 'your-domain.com' with your actual domain name !!!
      - "traefik.http.routers.my-website-https.rule=Host(`gazaka.com`)"
      - "traefik.http.routers.my-website-https.entrypoints=websecure"
      - "traefik.http.routers.my-website-https.tls=true"
      # !!! Check your main Traefik config for this resolver name (e.g., 'letsencrypt') !!!
      - "traefik.http.routers.my-website-https.tls.certresolver=myresolver" 

      # --- Service Configuration: Pointing Traefik to the Correct Port ---
      # This tells Traefik to forward traffic to this container's internal port 80
      - "traefik.http.services.my-website.loadbalancer.server.port=80"
    depends_on:
      - proxy

  proxy:
    build:
      context: ./proxy
    env_file:
      - .env
    # The proxy should also be on the t3_proxy network if Traefik needs to access it.
    networks:
      - t3_proxy

# Define the external Traefik network here so Docker Compose knows it exists.
networks:
  t3_proxy:
    external: true