version: '3.8'
services:
  # This is our existing frontend web server
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html

  # This is our new backend proxy server
  proxy:
    build:
      context: ./proxy # Tell Docker to look in the proxy folder
    ports:
      - "3000:3000"