version: '3.8'
services:
  # This is your existing frontend web server
  web:
    build: .
    ports:
      - "2525:80"
    volumes:
      - ./src:/usr/share/nginx/html

  # This is our backend proxy server
  proxy:
    build:
      context: ./proxy # Tell Docker to look in the proxy folder
    ports:
      - "2626:3000"
    # ADD THIS SECTION
    env_file:
      - .env  # This explicitly tells Docker to load variables from the .env file